### ISSUE TITLE
Parcels/ROIs are lost when converting ggseg3d atlas to ggseg

### ISSUE THREAD

**Issue by jorittmo** [ggseg/ggsegExtra#58]
Hi and thanks for all the work on these packages!

I noticed that the Schaefer2018_1000Parcels_7Networks atlas was actually made from Schaefer2018_900Parcels_7Networks and that some of the parcels/ROIs seemed to have been lost. So to fix this I tried to create a new ggseg Schaefer2018_1000Parcels_7Networks atlas. While I managed to create the atlas after some tinkering it seems like 44 parcels/ROIs was lost during the conversion for me as well. Is there an obvious reason for this that I am missing and/or are there any arguments you would recommend be to look at? (I have tried various smoothing terms but I think that the loss happens earlier in the pipeline).

Attached is an image of the resulting data (where I would expect schaef1k$data to have 1000 rows (or 1002 counting background).
![image](https://github.com/ggseg/ggsegExtra/assets/62261432/d4cc72e7-f59d-4ac1-a6b7-239a5f21897d)

Thanks for any help!
// Jonathan

**Comment by jorittmo** [comment]
Thank you for the fast reply! And that seems reasonable for some of the parcels. However, some of them seems to just have gotten lost (as can be seen in the image). 


```
library(ggsegExtra)
library(ggseg)
library(ggseg3d)
shaef_annot <- make_aparc_2_3datlas(annot = "Schaefer2018_1000Parcels_7Networks_order")

schaef1k <- make_ggseg3d_2_ggseg(
  ggseg3d_atlas = as_ggseg3d_atlas(shaef_annot),
  steps = 1:7, 
  output_dir = '/home/jorittmo/repositories/fmri_project1/output/ggseg_atlas_schaef',
  smoothness = 5,
  tolerance = 0,
  ncores = 11)

ggplot() +
  geom_brain(atlas = schaef1k, show.legend = FALSE,
             position = position_brain(side~hemi)) +
  theme_brain2()
```


![image](https://github.com/ggseg/ggsegExtra/assets/62261432/33ed24e0-ac61-4777-9c98-8888b9a4758a)

**Comment by drmowinckels** [comment]
nr. 1 - Awesome that you got ggsegExtra to work! I've not really got any feedback on that package from other users, so I am so happy to see it actually getting the job done.
nr. 2 - not entirely getting the job done, obviously! This reprex is awesome! Thank you for taking the time to make it, showing very clearly how you got there and what is missing.

indeed, there seems definitely to be a problem here. and i'll see to go digging into the ggsegExtra code I think, to find this. My first thought was that the tolerance might be messing something up, but I see you set that to 0, so that should not be it.

And the 3d atlas looks ok? Sorry for the questions, I have a new computer and its not yet setup to run ggsegExtras many dependencies, so need a little time to run it myself.

**Comment by jorittmo** [comment]
No rush! I'll try to rerun it myself soon to see if the result varies and if it was just some idiosyncrasies on my end causing the issue. The 3d atlas looks great. If I get it to work I'll make sure to make a pull request to the ggsegSchaefer repo.

Again, thanks for the work here, really appreciate it and will try to contribute where I can :)

**Comment by jorittmo** [comment]
Hey again! I've finally looked into this and I'm relatively sure it's the parallel file writing/reading that's the problem. I haven't figured out exactly where it happens in the pipeline and where to add extra checks, but a workaround if anyone else runs into this problem is to only use a single core or run the pipeline multiple times and join the idiosyncratic results
